### ISSUE TITLE
[bigquery] notifier fails to insert messages missing step Timing information

### ISSUE THREAD

**Issue by devjgm** [GoogleCloudPlatform/cloud-build-notifiers#115]
In fixing https://github.com/GoogleCloudPlatform/cloud-build-notifiers/issues/110, @prabenzom discovered that build notifications are often missing `step.Timing` information. This appears to be the case for most/all non-SUCCESSFUL statuses. **The end result is that most/all non-SUCCESSful status notifications get dropped on the floor and the data in BQ is woefully inaccurate.**

Example error message:
```
"E0527 00:54:23.418135       1 notifiers.go:449] failed to run SendNotification: Error inserting row into BQ: 1 row insertion failed (insertion of row [insertID: "YuH2meB46KYBgLxZNid82J1zGHU"; insertIndex: 0] failed with error: {Location: "steps[5].endtime"; Message: "Invalid datetime string \"0000-00-00 00:00:00\""; Reason: "invalid"})"
```

The relevant piece of code is here:
https://github.com/GoogleCloudPlatform/cloud-build-notifiers/blob/701ad5f51953544f208f17503e2c69463e6119bf/bigquery/main.go#L237-L257

# Proposed fix

Somehow, build notifications that are missing `step.Timing` information should NOT be dropped on the floor. So if the BQ schema requires that non-empty timing information be present, then I think some default timing info should be set for the steps.

* Maybe you could use the overall [`startTime`](https://github.com/GoogleCloudPlatform/cloud-build-notifiers/blob/701ad5f51953544f208f17503e2c69463e6119bf/bigquery/main.go#L228) and [`finishTime`](https://github.com/GoogleCloudPlatform/cloud-build-notifiers/blob/701ad5f51953544f208f17503e2c69463e6119bf/bigquery/main.go#L232)
* Maybe you could just set them to some default golang epoch value
* Something else

**Comment by prabenzom** [comment]
This should be fixed now
