### ISSUE TITLE
Please update Secret Manager name in repository description

### ISSUE THREAD

**Issue by sethvargo** [GoogleCloudPlatform/cloud-build-notifiers#119]
The current repository description is:

> Notifier images for Cloud Build, complete with build status filtering and Cloud Secret Manager integration

Could we please update the name of Secret Manager? It's either "Google Secret Manager" or "Secret Manager". There is no "Cloud" in the name.

> Notifier images for Cloud Build, complete with build status filtering and Google Secret Manager integration.

/cc @bendory

**Comment by bendory** [comment]
Done, thanks!
