### ISSUE TITLE
allow optional configuration of log levels

### ISSUE THREAD

**Issue by tgjonestx** [GoogleCloudPlatform/cloud-build-notifiers#147]
Currently configuration of the logger can only be controlled from the command line which is hard-coded in the `Dockerfile`.  For debugging notifiers, including custom notifiers, it would be nice if the notifier configuration supported optional parameters that allowed for the configuration of the logger (e.g. log level = debug).   

If the configuration properties for logging are not specified, then the notifier should default to the current behavior.

**Comment by vicpadilla** [comment]
Not the easiest solution, but you can override the command line args in cloud run when deploying the service. Example:

```
gcloud run deploy gcb-notifier-bigquery \
   --image=us-east1-docker.pkg.dev/gcb-release/cloud-build-notifiers/bigquery:latest \
   --no-allow-unauthenticated \
   --update-env-vars=CONFIG_PATH=gs://$BUCKET/bigquery-config.yaml,PROJECT_ID=$PROJECT \
   --command=/go-app --args=--alsologtostderr,--v=2
```

Alternatively, you can edit an existing Run service ("Edit & deploy new revision") and provide the "Container command" and "Container arguments" fields.
