### ISSUE TITLE
[SLACK NOTIFIER] Region not contained in the url

### ISSUE THREAD

**Issue by jknezevic** [GoogleCloudPlatform/cloud-build-notifiers#148]
I've set up the notifier using instructions from the official GCP page: https://cloud.google.com/build/docs/configuring-notifications/configure-slack

The messages are sent to the Slack channel, but without region, causing the GCP to throw an "Unable to find the resource that you requested" error. 

Is it possible to somehow create a proper URL, with a region? Is some extra coding required or have I failed to set the hook properly? 

Example: 
The link on the slack channel: 
```
https://console.cloud.google.com/cloud-build/builds/<build-id>?project=<project-id>&utm_campaign=google-cloud-build-notifiers&utm_medium=chat&utm_source=google-cloud-build
```
While it should be:

```
https://console.cloud.google.com/cloud-build/builds;region=<region>/<build-id>?project=<project-id>&utm_campaign=google-cloud-build-notifiers&utm_medium=chat&utm_source=google-cloud-build
```

**Comment by jknezevic** [comment]
@Aric1088 Sorry for the tag, but I see that you are the main contributor to this repo; would you be kind to take a look at this? I'd really appreciate it.

**Comment by fbozic** [comment]
We are interested in this as well, any updates?

**Comment by vicpadilla** [comment]
It seems to be fixed now. If this is still an issue on your side, could you share the json template that you are using for your slack notifier?
