### ISSUE TITLE
Not able to use GCP Cloud Build Trigger Name in Email Subject or Body

### ISSUE THREAD

**Issue by pranav-makwana** [GoogleCloudPlatform/cloud-build-notifiers#151]
I have tried to add to Trigger name in Subject but getting error while build the docker image. 
Attached screenshot for reference.
<img width="670" alt="image" src="https://user-images.githubusercontent.com/106136112/195077041-2cf5fc9b-b3ee-4d57-945f-07869c967435.png">
<img width="968" alt="image" src="https://user-images.githubusercontent.com/106136112/195077100-0ffd307b-fa30-437f-8019-31e6812f0109.png">

**Comment by kutysam** [comment]
isn't it supposed to be capital N, Name as opposed to name.

**Comment by kutysam** [comment]
btw, you can't get trigger name to appear sadly.

**Comment by kutysam** [comment]
{{.Build.Substitutions.TRIGGER_NAME}} use this. it works.
