### ISSUE TITLE
New line in a substitution fails Slack notification

### ISSUE THREAD

**Issue by AykutCevik** [GoogleCloudPlatform/cloud-build-notifiers#159]
For the Slack notifier I added the commit message via the CloudBuild trigger substition into a new section for the Slack message:
```
{
    "type": "section",
    "text": {
      "type": "mrkdwn",
      "text": "Message: {{.Build.Substitutions._COMMIT_MESSAGE}}"
    }
  },
```

Unfortunately, this fails now since the commit message contains new lines:

`notifiers.go:549] failed to run SendNotification: failed to write Slack message: failed to unmarshal templating JSON: invalid character '\n' in string literal"`

As I understand, the value should be sanitized with a filter function in the template (json). Is this something I can do directly in the template or is this a needed fix for the cloud-build-notifier?

**Comment by prabenzom** [comment]
Hi,

Yes, this project is being maintained. We just released a new image It looks like the issue you mentioned needs to be fixed in the notifier. I don't have a timeline on when someone on our team can take a look at this, but we're happy to take a look at any PRs that fix this issue.

**Comment by vicpadilla** [comment]
Can you try adding `|js` function to the commit_message value?:

```
  "text": "Message: {{.Build.Substitutions._COMMIT_MESSAGE | js}}"
```

This should escape the string in a way that is compatible with Javascript / JSON.

**Comment by AykutCevik** [comment]
Unfortunately, it didn't solve it. When `.Build.Substitutions._COMMIT_MESSAGE` contains a `'` in the message, the notifier fails with following error:
`failed to run SendNotification: failed to write Slack message: failed to unmarshal templating JSON: invalid character '\'' in string escape code"`

It doesnt' seem to escape that correctly. Without the `js` filter it fails sending messages which contain `\n`. 

Any ideas? Also please reopen. Thanks!

**Comment by AykutCevik** [comment]
I was now able to workaround this:
`{{$A := replace .Build.Substitutions._COMMIT_MESSAGE "'" "-" }}{{$A | js}}`
