### ISSUE TITLE
The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable

### ISSUE THREAD

**Issue by ShreyaGupta03** [GoogleCloudPlatform/cloud-build-notifiers#162]
When trying to deploy --image=us-east1-docker.pkg.dev/gcb-release/cloud-build-notifiers/smtp:latest in my project, I get the below error-
**The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable**

**Comment by ShreyaGupta03** [comment]
Any help would be appreciated to solve this error.

**Comment by arrighidante** [comment]
Same here. project id, bucket, etc, everything´s looking good but I get the same error. I´ll be around! Please, share when you solve this.

**Comment by ShreyaGupta03** [comment]
So far I am unable to solve this error so had to use a different image for this purpose.

**Comment by wonseok5** [comment]
what i do is just follow gcp docs. but that error occurs. it should be fixed as soon as possible.

**Comment by vicpadilla** [comment]
Turns out we had some errors in the documentation:

The yaml file for the notifier configuration mentioned a variable `${build.status}`. This has to be done with parenthesis instead of brackets: `$(build.status)`.

After adjusting this in the notifier config yaml, the issue should be gone.
