### ISSUE TITLE
what is the upgrade path for slack notifier versions < 0.15.0

### ISSUE THREAD

**Issue by tgjonestx** [GoogleCloudPlatform/cloud-build-notifiers#198]
Two years ago, this comment was added to the [README.md](slack/README.md)  for the slack notifier

> Please do not upgrade to 1.15 as it contains bindings/templating functionality which may break existing slack setups below 1.15. Official documentation will be released detailing usage for bindings/templating, but for now the feature is in alpha so existing users are recommended to use releases older than 1.15.

From release history, I see that versions 0.15.0 and 0.16.0 were marked "Pre-release", but there have been multiple releases since then without clarification as to how older implementations should upgrade.  Is the section for **Slack BlockKit Template Functions** supposed to be used by older implementations to upgrade?

**Comment by Aric1088** [comment]
Yes. See this PR for the added functionality in newer versions: https://github.com/GoogleCloudPlatform/cloud-build-notifiers/pull/134/files
