### ISSUE TITLE
Huge delay between build and status

### ISSUE THREAD

**Issue by Philmod** [GoogleCloudPlatform/cloud-build-notifiers#71]
The statuses sent to Slack often happened hours/days after it actually happened on GCB.

A last example is a finished build's status was sent 30 hours after to Slack.

![Cloud Run Log](https://user-images.githubusercontent.com/818310/93338339-3d436b00-f7f8-11ea-8b7f-27d87275fbd9.png)
![Build](https://user-images.githubusercontent.com/818310/93338349-3e749800-f7f8-11ea-83ac-6135bb0dbfcd.png)

**Comment by LOZORD** [comment]
It might be worth it to look at the [`publishTime` in the Pub/Sub payload](https://cloud.google.com/pubsub/docs/reference/rest/v1/PubsubMessage) - I can't immediately think of anything in this codebase that would cause the delay.

**Comment by LOZORD** [comment]
This has been resolved with #72 .
