### ISSUE TITLE
Lack of IGNORE_BAD_MESSAGES is logged

### ISSUE THREAD

**Issue by steelbrain** [GoogleCloudPlatform/cloud-build-notifiers#75]
I'm seeing a lot of this in stderr, and it's not useful or relevant for end-users. Maybe remove it?

```
env var "IGNORE_BAD_MESSAGES" is empty
```

**Comment by LOZORD** [comment]
Good catch, that's just log spam for the env var that was added in #72 . You can safely ignore it for now - it should only log on notifier startup (which could happen if Cloud Run is halting and reviving the notifier image frequently). 

If you want, you can file a PR to change the `log.Warningf` in `GetEnv` to a `log.V(2).Infof`. The log is only there for debugging, so gating it on a `-v` flag is fine with me.
