### ISSUE TITLE
unmarshal error thrown for pubsub notifications in slack and smtp notifiers

### ISSUE THREAD

**Issue by ggprod** [GoogleCloudPlatform/cloud-build-notifiers#77]
I recently (last week) deployed slack and smtp notifiers for some Cloud Builds from this repo using the automated setup.sh script approach as described [here](https://cloud.google.com/cloud-build/docs/configuring-notifications/configure-slack#automating_notification_configuration_for_slack) and [here](https://cloud.google.com/cloud-build/docs/configuring-notifications/configure-smtp#automating_notification_configuration_for_smtp).

I deployed them in 2 projects.  In one of the projects the notifications (or at least some of them) are coming through and I do see logs of valid pubsub messages received and processed amidst the errors.  In the other projects I don't see any logs of valid messages received and processed and am not receiving any of the notifications.

I'm including screenshots of Cloud logging logs related to the error (which is from line 410 of notifiers.go [here](https://github.com/GoogleCloudPlatform/cloud-build-notifiers/blob/master/lib/notifiers/notifiers.go#L410) ) as well as the logs of the valid received/processed pubsub notifications

<img width="1470" alt="Screen Shot 2020-11-01 at 2 26 03 PM" src="https://user-images.githubusercontent.com/7189862/97812419-3c06ba00-1c4f-11eb-937e-fc595a780a8b.png">
<img width="1443" alt="Screen Shot 2020-11-01 at 2 26 52 PM" src="https://user-images.githubusercontent.com/7189862/97812422-41640480-1c4f-11eb-8333-430cc3f0acd8.png">
<img width="1434" alt="Screen Shot 2020-11-01 at 2 28 14 PM" src="https://user-images.githubusercontent.com/7189862/97812426-46c14f00-1c4f-11eb-95a0-54e47003aa8c.png">

**Comment by LOZORD** [comment]
Hi Mark, can you show me what the error is? It should be the last chunk of the log that you provided. Also, when running setup.sh for the second project, did you run `gcloud config set project $SECOND_PROJECT_ID`?

**Comment by ggprod** [comment]
hi @LOZORD sure, here is that last bit.  Yes, for the second project I did update gcloud to point to the new project and verified everything was deployed to that project correctly (pubsub topic, cloud run service, etc..)

![Screen Shot 2020-11-02 at 10 35 59 AM](https://user-images.githubusercontent.com/7189862/97887097-6dd35b80-1cf7-11eb-9922-b7269782b6eb.png)

**Comment by LOZORD** [comment]
Awesome, this is definitely not good 😨 I think I found the issue. According to my records, we add the CLOUD_LOGGING enum in July but our version of the Build proto library is from April (ugh) (`google.golang.org/genproto v0.0.0-20200413115906-b5235f65be36` from the go.mod). Updating it should resolve this issue.

**Comment by ggprod** [comment]
Thanks for the quick turnaround @LOZORD I'll reinstall and test to verify.

**Comment by LOZORD** [comment]
Great! I _just_ released new versions, so you may want to verify that you're pulling `us-east1-docker.pkg.dev/gcb-release/cloud-build-notifiers/slack@sha256:c06a7b2019f9e3b7a69712c44353747688d175432be13781bc5746251690e86f` for example.

**Comment by ggprod** [comment]
yes, this issue appears to be resolved now.. Thanks @LOZORD !
