### ISSUE TITLE
Add trigger name to slack notification

### ISSUE THREAD

**Issue by bouk** [GoogleCloudPlatform/cloud-build-notifiers#90]
Thanks for this project, it's super useful. I'd love it if you added the name of the trigger to the slack notification, which would make it easier to see what a notification is for

**Comment by LOZORD** [comment]
You're welcome 😄 I totally agree - for silly reasons we don't include the trigger name in the Pub/Sub payload (or Build resource for that matter). Until we provide the trigger name in the payload or provide it as an available substitution, the best alternative is to stick a GCB gRPC (or JSON) [client](https://pkg.go.dev/google.golang.org/genproto/googleapis/devtools/cloudbuild/v1#CloudBuildClient) in the notifier and call `GetBuildTrigger`, which should include the trigger name.

Please feel free to send a PR for this functionality as others would definitely benefit!

**Comment by bouk** [comment]
PR submitted #91

**Comment by jrissler** [comment]
+1 this is really useful project. This feature would be ultra useful - otherwise given you have multiple apps being triggered doesn't appear to be a way to distinguish them.

**Comment by LOZORD** [comment]
Hi all! We on Cloud Build are aware of this need but want to have a standardized implementation for all notifiers, so I filed #95. We're currently waiting on our PM to share a doc in this repo for this set of features. I can't give a timeline, but I was told Soon ™️ . The implementation will be open to the community to code up.

**Comment by vicpadilla** [comment]
You can use {{.Build.Substitutions.TRIGGER_NAME}} in the template to get the trigger name.
