### ISSUE TITLE
Secrets can't be read across projects

### ISSUE THREAD

**Issue by jakebiesinger-storyhealth** [GoogleCloudPlatform/cloud-build-notifiers#92]
I have a bunch of projects that each run separate cloudbuild deployments. To simplify life, my Slack webhook URL is not replicated across these projects, although each project's cloudbuild service account has access to the secret.

So, I have cloud-build-notifiers running in projects 1-N, and the secret they need in project M. I pass in the full path to the secret, but apparently this is not allowed:

```
1 main.go:33] fatal error: failed to call SetUp on notifier: failed to get token secret: failed to get secret named "projects/some-project/secrets/cloud-build-slack-webhook-url": rpc error: code = InvalidArgument desc = Resource ID [projects/some-project/secrets/cloud-build-slack-webhook-url] is not in a valid format.
```

**Comment by jakebiesinger-storyhealth** [comment]
bah, sorry for the noise. Apparently I forgot to include the `/versions/latest` suffix on the secret in the other project.

**Comment by LOZORD** [comment]
No worries! Keep me posted if you run into any other issues with secrets.
