### ISSUE TITLE
Update Secret Manager usage from v1beta1 to v1 API

### ISSUE THREAD

**Issue by nickmunarriz** [GoogleCloudPlatform/cloud-build-notifiers#98]
`secretmanager.googleapis.com` has `v1beta1` and `v1` APIs. After Secret Manager went GA in March 2020, new features are only being added to the `v1 `version of the API.

**Comment by LOZORD** [comment]
If you want, you are welcome to file a PR!

**Comment by nickmunarriz** [comment]
Oops, forgot to close this out! PR was merged: https://github.com/GoogleCloudPlatform/cloud-build-notifiers/pull/99

**Comment by LOZORD** [comment]
I forgot too 😅 thanks!
